-- =============================================================
-- MCU — COMPLETE DATABASE SETUP (ALL-IN-ONE)
-- Paste this ENTIRE file into the Supabase SQL Editor and Run ONCE.
-- It rebuilds all tables, triggers, security policies, restores
-- user profiles from existing auth accounts, and seeds test data.
-- (Run admin.sql AFTER this file to set up the grading system.)
-- =============================================================


-- =============================================================
-- STEP 1: Safely clear existing custom tables
-- =============================================================
DROP TABLE IF EXISTS certificates CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS enrollments CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS instructors CASCADE;
DROP TABLE IF EXISTS departments CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS membershiptiers CASCADE;
DROP SEQUENCE IF EXISTS member_id_seq;


-- =============================================================
-- STEP 2: Membership Tiers Table
-- tierid identifies the membership tier. The catalogue fields are editable
-- from /admin/cms/membership after the membership CMS migration/policies run.
-- =============================================================
CREATE TABLE membershiptiers (
    tierid INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY
        CHECK (tierid BETWEEN 1 AND 99),
    membname VARCHAR(150) NOT NULL UNIQUE,
    tiers VARCHAR(150) NOT NULL,
    category VARCHAR(100) NOT NULL DEFAULT 'International',
    price NUMERIC(12, 2) CHECK (price IS NULL OR price >= 0),
    currency VARCHAR(3) NOT NULL DEFAULT 'USD'
        CHECK (currency = upper(currency) AND currency ~ '^[A-Z]{3}$'),
    period VARCHAR(40) NOT NULL DEFAULT '/ year',
    discountrate NUMERIC(3, 2) NOT NULL DEFAULT 0.00
        CHECK (discountrate >= 0.00 AND discountrate <= 1.00),
    description TEXT,
    features JSONB NOT NULL DEFAULT '[]'::jsonb,
    color VARCHAR(20) NOT NULL DEFAULT '#2EC4B6',
    highlight BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    stripe_price_id TEXT
);


-- =============================================================
-- STEP 3: Users Table (Linked to Supabase Auth UUID & Membership Tier)
-- tierid  : which tier they joined (1/2/3). NULL = not a member yet.
-- memberid: membership number (10001+). Assigned automatically by trigger
--           ONLY when the user joins a tier. NULL = no membership.
-- =============================================================
CREATE SEQUENCE IF NOT EXISTS member_id_seq START WITH 10001;

CREATE TABLE users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    memberid INT UNIQUE DEFAULT NULL CHECK (memberid IS NULL OR memberid >= 10001),
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    phone_number VARCHAR(20) DEFAULT NULL,
    area_of_interest VARCHAR(100) DEFAULT NULL,
    tierid INT DEFAULT NULL REFERENCES membershiptiers(tierid) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Assign a memberid automatically the FIRST time a user joins any tier.
-- If they later upgrade/downgrade tiers, the memberid stays the same.
CREATE OR REPLACE FUNCTION public.assign_member_id()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.tierid IS NOT NULL AND NEW.memberid IS NULL THEN
    NEW.memberid := nextval('member_id_seq');
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_membership_join ON public.users;
CREATE TRIGGER on_membership_join
  BEFORE INSERT OR UPDATE OF tierid ON public.users
  FOR EACH ROW EXECUTE FUNCTION public.assign_member_id();


-- =============================================================
-- STEP 4: Instructors Table
-- =============================================================
CREATE TABLE instructors (
    instructorid INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    specialization VARCHAR(150)
);


-- =============================================================
-- STEP 5: Courses Table (includes description used by the website)
-- =============================================================
CREATE TABLE courses (
    courseid INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    coursename VARCHAR(100) NOT NULL,
    coursetype VARCHAR(50) NOT NULL,
    price NUMERIC(8, 2) NOT NULL DEFAULT 0.00 CHECK (price <= 999999.99),
    description TEXT,
    instructorid INT REFERENCES instructors(instructorid) ON DELETE SET NULL
);


-- =============================================================
-- STEP 6: Enrollments Table (Linked directly to users UUID)
-- =============================================================
CREATE TABLE enrollments (
    enrollmentid INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    courseid INT NOT NULL REFERENCES courses(courseid) ON DELETE RESTRICT,
    enrollmentdate DATE DEFAULT CURRENT_DATE,
    paymentstatus VARCHAR(20) DEFAULT 'Pending'
        CHECK (paymentstatus IN ('Paid', 'Pending', 'Refunded')),
    grade VARCHAR(10) CHECK (grade IN ('Pass', 'Fail'))
);


-- =============================================================
-- STEP 7: Certificates Table
-- recipientname + coursename are snapshots saved at issue time,
-- auto-filled by the grading trigger (see admin.sql).
-- =============================================================
CREATE TABLE certificates (
    certificateid INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    enrollmentid INT UNIQUE NOT NULL REFERENCES enrollments(enrollmentid) ON DELETE CASCADE,
    certificatenumber VARCHAR(50) UNIQUE NOT NULL,
    recipientname VARCHAR(120),
    coursename VARCHAR(120),
    issuedate DATE DEFAULT CURRENT_DATE
);


-- =============================================================
-- STEP 8: AUTOMATIC AUTH TRIGGER (Saves Sign-Up data into `users`)
-- =============================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (
    id,
    email,
    first_name,
    last_name,
    phone_number,
    area_of_interest
  )
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'first_name', ''),
    COALESCE(NEW.raw_user_meta_data->>'last_name', ''),
    COALESCE(NEW.raw_user_meta_data->>'phone', ''),
    COALESCE(NEW.raw_user_meta_data->>'area_of_interest', '')
  )
  ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    phone_number = EXCLUDED.phone_number,
    area_of_interest = EXCLUDED.area_of_interest;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- =============================================================
-- STEP 9: ROW LEVEL SECURITY (RLS) POLICIES
-- =============================================================
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own profile" ON public.users
  FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can insert own profile" ON public.users
  FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile" ON public.users
  FOR UPDATE USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- Public catalogue tables: read-only access for everyone
ALTER TABLE public.membershiptiers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view membership tiers" ON public.membershiptiers
  FOR SELECT USING (active = TRUE);

ALTER TABLE public.instructors ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view instructors" ON public.instructors
  FOR SELECT USING (true);

ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view courses" ON public.courses
  FOR SELECT USING (true);

-- Enrollments: members can enroll themselves and see their own enrollments
ALTER TABLE public.enrollments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own enrollments" ON public.enrollments
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can enroll themselves" ON public.enrollments
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Certificates: students can view their own
ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own certificates" ON public.certificates
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.enrollments e
      WHERE e.enrollmentid = certificates.enrollmentid AND e.user_id = auth.uid()
    )
  );


-- =============================================================
-- STEP 10: RESTORE PROFILE ROWS for accounts that already signed up
-- (schema rebuild wiped the users table; this recreates every profile)
-- =============================================================
INSERT INTO public.users (id, email, first_name, last_name, phone_number, area_of_interest)
SELECT
  au.id,
  au.email,
  COALESCE(au.raw_user_meta_data->>'first_name', ''),
  COALESCE(au.raw_user_meta_data->>'last_name', ''),
  COALESCE(au.raw_user_meta_data->>'phone', ''),
  COALESCE(au.raw_user_meta_data->>'area_of_interest', '')
FROM auth.users au
ON CONFLICT (id) DO NOTHING;


-- =============================================================
-- STEP 11: SEED / TEST DATA
-- =============================================================

-- 11.1 Membership Tiers
INSERT INTO public.membershiptiers
  (tierid, membname, tiers, category, price, currency, period,
   discountrate, description, features, color, highlight, active, sort_order)
VALUES
  (1, 'VIP Gold International', 'VIP Gold', 'International', 50000.00, 'USD', '/ year', 0.10,
   'A prestigious international membership for professionals who want a strong foundation of access, learning and connection.',
   '["International member directory access", "Monthly executive webinars", "Priority invitations to MCU events", "10% discount on course enrolment", "Digital VIP Gold membership certificate"]'::jsonb,
   '#E5A52E', FALSE, TRUE, 1),
  (2, 'VIP Jade International', 'VIP Jade', 'International', 1000000.00, 'USD', '/ year', 0.20,
   'An elevated international membership for leaders seeking deeper access to MCU insight, networks and opportunities.',
   '["All VIP Gold benefits", "Private quarterly networking briefings", "Priority course registration", "20% discount on course enrolment", "Members-only research reports", "Dedicated relationship support"]'::jsonb,
   '#2EC4B6', TRUE, TRUE, 2),
  (3, 'VIP Black Diamond', 'VIP Black Diamond', 'International', 2000000.00, 'USD', '/ year', 0.30,
   'Our highest membership level for distinguished principals and institutions building a lasting global legacy.',
   '["All VIP Jade benefits", "Private advisory and strategy sessions", "VIP access to the annual conference", "30% discount on course enrolment", "Personal academic advisor", "Black Diamond member spotlight"]'::jsonb,
   '#1A1A2A', FALSE, TRUE, 3)
ON CONFLICT (tierid) DO UPDATE SET
  membname = EXCLUDED.membname,
  tiers = EXCLUDED.tiers,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  period = EXCLUDED.period,
  discountrate = EXCLUDED.discountrate,
  description = EXCLUDED.description,
  features = EXCLUDED.features,
  color = EXCLUDED.color,
  highlight = EXCLUDED.highlight,
  active = EXCLUDED.active,
  sort_order = EXCLUDED.sort_order;

-- 11.2 Instructors
INSERT INTO public.instructors (firstname, lastname, specialization)
VALUES
  ('Dr. Alexander', 'Wong', 'Wealth Planning & Estate Tax'),
  ('Sarah', 'Chen', 'Family Office Governance'),
  ('Michael', 'Tse', 'CFP Compliance & Financial Analysis');

-- 11.3 Sample Courses
INSERT INTO public.courses (coursename, coursetype, price, description, instructorid)
VALUES
  ('Professional Financial Planning Program', 'Financial Planning', 8500.00,
   'Comprehensive training in financial planning fundamentals and CFP-aligned practice.', 1),
  ('CEO Wealth Management Program', 'Wealth Management', 12500.00,
   'Executive-level wealth management strategies for business leaders.', 2),
  ('Family Office Wealth Management Program', 'Family Office', 15000.00,
   'Structuring, governance and investment management for family offices.', 2),
  ('Professional Family Office Consultant Program', 'Executive', 18000.00,
   'Advanced consultancy skills for serving ultra-high-net-worth families.', 3);


-- =============================================================
-- STEP 12: VERIFY — should show tiers=3, instructors=3, courses=4, users>=1
-- =============================================================
SELECT
  (SELECT COUNT(*) FROM public.membershiptiers) AS tiers,
  (SELECT COUNT(*) FROM public.instructors)     AS instructors,
  (SELECT COUNT(*) FROM public.courses)         AS courses,
  (SELECT COUNT(*) FROM public.users)           AS users;
