-- =============================================================
-- MCU — Database Schema (Tables + Triggers + RLS)
-- Run this FIRST in the Supabase SQL Editor.
-- Test/seed data lives separately in seed.sql.
-- =============================================================


-- =============================================================
-- STEP 1: Safely clear existing custom tables
-- =============================================================
DROP TABLE IF EXISTS certificates CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS enrollments CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS instructors CASCADE;
DROP TABLE IF EXISTS departments CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS membershiptiers CASCADE;
DROP SEQUENCE IF EXISTS member_id_seq;


-- =============================================================
-- STEP 2: Membership Tiers Table
-- tierid identifies the TIER itself: 1 = Standard, 2 = Professional, 3 = Premium
-- =============================================================
CREATE TABLE membershiptiers (
    tierid INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY
        CHECK (tierid BETWEEN 1 AND 99),
    membname VARCHAR(30) NOT NULL UNIQUE,
    tiers VARCHAR(30) NOT NULL,
    discountrate NUMERIC(3, 2) NOT NULL DEFAULT 0.00 CHECK (discountrate <= 1.00)
);


-- =============================================================
-- STEP 3: Users Table (Linked to Supabase Auth UUID & Membership Tier)
-- tierid  : which tier they joined (1/2/3). NULL = not a member yet.
-- memberid: membership number (10001+). Assigned automatically by trigger
--           ONLY when the user joins a tier. NULL = no membership.
-- =============================================================
CREATE SEQUENCE IF NOT EXISTS member_id_seq START WITH 10001;

CREATE TABLE users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    memberid INT UNIQUE DEFAULT NULL CHECK (memberid IS NULL OR memberid >= 10001),
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    phone_number VARCHAR(20) DEFAULT NULL,
    area_of_interest VARCHAR(100) DEFAULT NULL,
    tierid INT DEFAULT NULL REFERENCES membershiptiers(tierid) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Assign a memberid automatically the FIRST time a user joins any tier.
-- If they later upgrade/downgrade tiers, the memberid stays the same.
CREATE OR REPLACE FUNCTION public.assign_member_id()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.tierid IS NOT NULL AND NEW.memberid IS NULL THEN
    NEW.memberid := nextval('member_id_seq');
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_membership_join ON public.users;
CREATE TRIGGER on_membership_join
  BEFORE INSERT OR UPDATE OF tierid ON public.users
  FOR EACH ROW EXECUTE FUNCTION public.assign_member_id();


-- =============================================================
-- STEP 4: Instructors Table
-- =============================================================
CREATE TABLE instructors (
    instructorid INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    specialization VARCHAR(150)
);


-- =============================================================
-- STEP 5: Courses Table
-- (includes `description`, which app/courses/page.tsx selects)
-- =============================================================
CREATE TABLE courses (
    courseid INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    coursename VARCHAR(100) NOT NULL,
    coursetype VARCHAR(50) NOT NULL,
    price NUMERIC(8, 2) NOT NULL DEFAULT 0.00 CHECK (price <= 999999.99),
    description TEXT,
    instructorid INT REFERENCES instructors(instructorid) ON DELETE SET NULL
);


-- =============================================================
-- STEP 6: Enrollments Table (Linked directly to users UUID)
-- =============================================================
CREATE TABLE enrollments (
    enrollmentid INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    courseid INT NOT NULL REFERENCES courses(courseid) ON DELETE RESTRICT,
    enrollmentdate DATE DEFAULT CURRENT_DATE,
    paymentstatus VARCHAR(20) DEFAULT 'Pending'
        CHECK (paymentstatus IN ('Paid', 'Pending', 'Refunded')),
    grade VARCHAR(10) CHECK (grade IN ('Pass', 'Fail'))
);


-- =============================================================
-- STEP 7: Certificates Table
-- =============================================================
CREATE TABLE certificates (
    certificateid INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    enrollmentid INT UNIQUE NOT NULL REFERENCES enrollments(enrollmentid) ON DELETE CASCADE,
    certificatenumber VARCHAR(50) UNIQUE NOT NULL,
    issuedate DATE DEFAULT CURRENT_DATE
);


-- =============================================================
-- STEP 8: AUTOMATIC AUTH TRIGGER (Saves Sign-Up data into `users`)
-- =============================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (
    id,
    email,
    first_name,
    last_name,
    phone_number,
    area_of_interest
  )
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'first_name', ''),
    COALESCE(NEW.raw_user_meta_data->>'last_name', ''),
    COALESCE(NEW.raw_user_meta_data->>'phone', ''),
    COALESCE(NEW.raw_user_meta_data->>'area_of_interest', '')
  )
  ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    phone_number = EXCLUDED.phone_number,
    area_of_interest = EXCLUDED.area_of_interest;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger firing on auth.users sign ups
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- =============================================================
-- STEP 9: ROW LEVEL SECURITY (RLS) POLICIES
-- =============================================================
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own profile" ON public.users
  FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can insert own profile" ON public.users
  FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile" ON public.users
  FOR UPDATE USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- Public catalogue tables: enable RLS with read-only access for everyone,
-- so the courses & membership pages work for both anon and logged-in users.
ALTER TABLE public.membershiptiers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view membership tiers" ON public.membershiptiers
  FOR SELECT USING (true);

ALTER TABLE public.instructors ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view instructors" ON public.instructors
  FOR SELECT USING (true);

ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view courses" ON public.courses
  FOR SELECT USING (true);

-- Enrollments: members can enroll themselves and see their own enrollments.
ALTER TABLE public.enrollments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own enrollments" ON public.enrollments
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can enroll themselves" ON public.enrollments
  FOR INSERT WITH CHECK (auth.uid() = user_id);
