'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import SiteLayout from '@/components/SiteLayout';
import AdminGuard from '@/components/AdminGuard';
import { createClient } from '@/lib/supabase/client';

type Product={productid:number;title:string;category:string|null;price:string;description:string|null;image_url:string|null;active:boolean;sort_order:number;badge:string|null};
const blank: Omit<Product,'productid'>={title:'',category:'',price:'',description:'',image_url:'',active:true,sort_order:0,badge:''};
export default function ProductsCMS(){const [rows,setRows]=useState<Product[]>([]);const [edit,setEdit]=useState<Product|null>(null);const [busy,setBusy]=useState(false);const db=createClient();
const load=async()=>{const {data}=await db.from('products').select('*').order('sort_order');setRows((data||[]) as Product[])};useEffect(()=>{load()},[]);
async function upload(file:File){if(!edit)return;setBusy(true);const path=`products/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const {error}=await db.storage.from('cms').upload(path,file);if(error)alert(error.message);else{const {data}=db.storage.from('cms').getPublicUrl(path);setEdit({...edit,image_url:data.publicUrl})}setBusy(false)}
async function save(){if(!edit||!edit.title||!edit.price)return alert('Title and price are required.');setBusy(true);const {productid,...payload}=edit;const result=productid?await db.from('products').update(payload).eq('productid',productid):await db.from('products').insert(payload);if(result.error)alert(result.error.message);else{setEdit(null);await load()}setBusy(false)}
async function remove(id:number){if(confirm('Delete this product?')){await db.from('products').delete().eq('productid',id);load()}}
return <AdminGuard><SiteLayout><main style={{padding:'130px 24px 80px',background:'#F8F8FA',minHeight:'80vh'}}><div className="container"><Link href="/admin/cms">← Back to Content Manager</Link><h1 style={{margin:'18px 0'}}>Shop Products</h1><button onClick={()=>setEdit({productid:0,...blank})} style={button}>+ Add product</button><div style={{display:'grid',gridTemplateColumns:edit?'1fr 380px':'1fr',gap:24,marginTop:20}}><section style={panel}>{rows.map(p=><div key={p.productid} style={row}><img src={p.image_url||'/placeholder.png'} alt="" style={{width:70,height:55,objectFit:'cover',borderRadius:8,background:'#eee'}}/><div style={{flex:1}}><b>{p.title}</b><div style={{color:'#666'}}>{p.category} · {p.price}</div></div><button onClick={()=>setEdit(p)} style={small}>Edit</button><button onClick={()=>remove(p.productid)} style={{...small,color:'#b22'}}>Delete</button></div>)}</section>{edit&&<Editor title={edit.title} onSave={save} onCancel={()=>setEdit(null)} busy={busy}><Field label="Title" value={edit.title} onChange={v=>setEdit({...edit,title:v})}/><Field label="Category" value={edit.category||''} onChange={v=>setEdit({...edit,category:v})}/><Field label="Price" value={edit.price} onChange={v=>setEdit({...edit,price:v})}/><Field label="Description" area value={edit.description||''} onChange={v=>setEdit({...edit,description:v})}/><label>Photo<input type="file" accept="image/*" onChange={e=>e.target.files&&upload(e.target.files[0])}/></label>{edit.image_url&&<img src={edit.image_url} alt="Preview" style={{display:'block',width:'100%',maxWidth:'100%',height:130,objectFit:'contain',marginTop:8,borderRadius:8,background:'#f2f2f2'}}/>}</Editor>}</div></div></main></SiteLayout></AdminGuard>}
function Field({label,value,onChange,area}:{label:string;value:string;onChange:(v:string)=>void;area?:boolean}){return <label style={{display:'block',fontWeight:600,fontSize:13}}>{label}{area?<textarea value={value} onChange={e=>onChange(e.target.value)} style={input} rows={4}/>:<input value={value} onChange={e=>onChange(e.target.value)} style={input}/>}</label>};function Editor(p:any){return <aside style={panel}><h2>{p.title?'Edit':'Add'} item</h2><div style={{display:'grid',gap:14}}>{p.children}</div><button disabled={p.busy} onClick={p.onSave} style={{...button,marginTop:18}}>{p.busy?'Saving…':'Save'}</button><button onClick={p.onCancel} style={small}>Cancel</button></aside>};const panel={background:'#fff',borderRadius:16,padding:22,border:'1px solid #eee'};const row={display:'flex',alignItems:'center',gap:14,padding:'14px 0',borderBottom:'1px solid #eee'};const input={display:'block',width:'100%',padding:10,border:'1px solid #ddd',borderRadius:8,marginTop:5};const button={background:'#7B1A2D',color:'#fff',border:0,borderRadius:24,padding:'11px 18px',fontWeight:700};const small={background:'none',border:0,color:'#7B1A2D',fontWeight:700,padding:8};
